matrix:
  include:
    - os: osx
    - os: linux
      sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull $DOCKER_IMAGE; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./scripts/travis-build-wheels.sh $TRAVIS_OS_NAME; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/scripts/travis-build-wheels.sh $TRAVIS_OS_NAME; fi
  - ls wheelhouse/
