environment:
  matrix:
    - PYARCH: ""
      RUST_TARGET: "i686-pc-windows-msvc"
    - PYARCH: "-x64"
      RUST_TARGET: "x86_64-pc-windows-msvc"

install:
  - ps: |
      $PyVersions = @("35")
      foreach ($pyver in $PyVersions) {
        $python = "C:\\Python$pyver${env:PYARCH}\\python"
        &$python -m pip install -U pip setuptools wheel Cython numpy
      }
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %RUST_TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin

build_script:
  - pushd .\\noise-c && cargo build --release && popd
  - ps: |
      $PyVersions = @("35")
      foreach ($pyver in $PyVersions) {
        $python = "C:\\Python$pyver${env:PYARCH}\\python"
        &$python -m pip -v wheel . -w .\\wheelhouse
      }
  - dir wheelhouse

test_script:
  - SET PROJPATH=C:\Projects\noisily
  - cd c:\projects
  - ps: |
      $PyVersions = @("35")
      foreach ($pyver in $PyVersions) {
        $python = "C:\\Python$pyver${env:PYARCH}\\python"
        &$python -m pip -v install noisily --no-index -f "${env:PROJPATH}\\wheelhouse"
        &$python -m pip install -U pytest
        &$python -m pytest "${env:PROJPATH}\\tests"
      }

artifacts:
  - path: wheelhouse\noisily*.whl
